### ISSUE TITLE
How to save user details to the vcard?

### ISSUE THREAD

**Issue by merbin2012** [ggozad/strophe.plugins#3]
I am using converse.js and strophe for register the user, but when I am register using strophe.register.js it will not save the vcard details. So I can not able to see the users full name in the contact list. Do I need any other plugin or other methods for save the vcard details?

**Comment by ggozad** [comment]
I think you got the wrong plugin repository :)
Not sure if you use my plugins or somebody else's as there is no register on my side.
If you use mine, you can use the vCard plugin to save vcards.
